PG_CONFIG ?= pg_config

LZ4_LIB := $(shell /sbin/ldconfig -p | grep lz4)

ifeq ($(LZ4_LIB),)
$(error LZ4 library not installed)
endif

PGXS := $(shell $(PG_CONFIG) --pgxs)
PG_LIB := $(shell $(PG_CONFIG) --pkglibdir)
INCLUDEDIR := ${shell $(PG_CONFIG) --includedir}
INCLUDEDIR_SERVER := ${shell $(PG_CONFIG) --includedir-server}

USE_PGXS = 1
include $(PGXS)
