SET duckdb.force_execution = true;
CREATE TABLE ta(a INT);
EXPLAIN SELECT * FROM ta;
EXPLAIN VERBOSE SELECT * FROM ta;

INSERT INTO ta VALUES(1);
INSERT INTO ta VALUES(2);
INSERT INTO ta VALUES(3);
ANALYZE ta;

EXPLAIN SELECT * FROM ta;
EXPLAIN VERBOSE SELECT * FROM ta;
EXPLAIN SELECT count(*) FROM ta;
EXPLAIN VERBOSE SELECT count(*) FROM ta;
DROP TABLE ta;
