CREATE TABLE t(a INT, b VARCHAR);
INSERT INTO t SELECT g % 100, MD5(g::VARCHAR) FROM generate_series(1,1000) g;
SELECT COUNT(*) FROM t WHERE a % 10 = 0;
CREATE MATERIALIZED VIEW tv AS SELECT * FROM t WHERE a % 10 = 0;
SELECT COUNT(*) FROM tv;

INSERT INTO t SELECT g % 100, MD5(g::TEXT) FROM generate_series(1,1000) g;
SELECT COUNT(*) FROM t WHERE a % 10 = 0;

REFRESH MATERIALIZED VIEW tv;
SELECT COUNT(*) FROM tv;


SELECT COUNT(*) FROM t WHERE (a % 10 = 0) AND (a < 3);
SELECT COUNT(*) FROM tv WHERE a < 3;

DROP MATERIALIZED VIEW tv;
DROP TABLE t;
