CREATE TABLE t(a INT, b TEXT);
INSERT INTO t SELECT g % 1000, MD5(g::TEXT) FROM generate_series(1,20000) g;
SELECT COUNT(*) FROM t WHERE a % 100 = 0;
CREATE MATERIALIZED VIEW tv AS SELECT * FROM t WHERE a % 100 = 0;
SELECT COUNT(*) FROM tv;

INSERT INTO t SELECT g % 1000, MD5(g::TEXT) FROM generate_series(1,20000) g;
SELECT COUNT(*) FROM t WHERE a % 100 = 0;

REFRESH MATERIALIZED VIEW tv;
SELECT COUNT(*) FROM tv;


SELECT COUNT(*) FROM t WHERE (a % 100 = 0) AND (a < 30);
SELECT COUNT(*) FROM tv WHERE a < 30;

DROP MATERIALIZED VIEW tv;
DROP TABLE t;
